// Auto-generated by: npx supabase gen types typescript --local > types/database.ts
// This file will be replaced once Supabase migrations are applied (Task 2)

export type Database = {
  public: {
    Tables: Record<string, never>
    Views: Record<string, never>
    Functions: Record<string, never>
    Enums: Record<string, never>
  }
}
